pipeline {
    agent any
    stages {
        stage('Docker Build image') {
            steps {
                sh '''
                  cd spring-petclinic/
                  echo 'building docker image'
                  sudo docker build -t demo:v1 .
                '''
                }
            }
        stage('Docker run') {
            steps {
                sh '''
                  sudo docker run -it -d -p 8096:8080 demo:v1

                '''
            }
        }
    }
}