apiVersion: apps/v1
kind: Deployment
metadata:
  name: trainschedule-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trainschedule
  template:
    metadata:
      labels:
        app: trainschedule
    spec:
      containers:
      - name: trainschedule
        image: oldcity255/docker_hub:v1
        ports:
        - containerPort: 8080