apiVersion: v1
kind: Service
metadata:
  name: trainschedule-service
spec:
  selector:
    app: trainschedule
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  clusterIP: 
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.70.123.125